### ISSUE TITLE
Can't hear me? Comment here.

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/dev-dec-19#2]
If you can't hear me, comment here please.

**Comment by naveenphd** [comment]
+1:: Not able hear

**Comment by hflora** [comment]
:+1:

**Comment by daleonpz** [comment]
cannot hear

**Comment by naveenphd** [comment]
yes

**Comment by githubteacher** [comment]
@crichID is going to help with the audio issues, please go to the Gitter chat room: https://gitter.im/githubteacher/dev-dec-19

**Comment by crichID** [comment]
@naveenphd @daleonpz If you are unable to hear @beardofedu you may want to try the phone call option in GoToWebinar!

**Comment by naveenphd** [comment]
no phone is not possible now

**Comment by JazzDeveloper** [comment]
Hello

**Comment by icodedude** [comment]
Yes
